// Generated by scripts/generate-writeup-index.mjs. Do not edit by hand.
export const writeupIndex = [
  {
    "path": "./writeups/boroctf-2026/index.mdx",
    "slug": "boroctf-2026",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "ctf",
    "title": "BoroCTF 2026 Writeups",
    "date": "2026-06-18",
    "order": 98
  },
  {
    "path": "./writeups/boroctf-2026/a-purpose-beyond-satoshi/index.mdx",
    "slug": "boroctf-2026-a-purpose-beyond-satoshi",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "A Purpose Beyond Satoshi — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 115
  },
  {
    "path": "./writeups/boroctf-2026/klaud-code/index.mdx",
    "slug": "boroctf-2026-klaud-code",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Klaud Code — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 183
  },
  {
    "path": "./writeups/boroctf-2026/my-mayor-muslim/index.mdx",
    "slug": "boroctf-2026-my-mayor-muslim",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "My Mayor Muslim... — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 181
  },
  {
    "path": "./writeups/boroctf-2026/omegacode/index.mdx",
    "slug": "boroctf-2026-omegacode",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "OmegaCode — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 204
  },
  {
    "path": "./writeups/boroctf-2026/player-2/index.mdx",
    "slug": "boroctf-2026-player-2",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Player 2 — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 157
  },
  {
    "path": "./writeups/boroctf-2026/satoshis-revenge/index.mdx",
    "slug": "boroctf-2026-satoshis-revenge",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Satoshi's Revenge — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 123
  },
  {
    "path": "./writeups/boroctf-2026/satoshis-secret/index.mdx",
    "slug": "boroctf-2026-satoshis-secret",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Satoshi's Secret — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 120
  },
  {
    "path": "./writeups/boroctf-2026/shiny/index.mdx",
    "slug": "boroctf-2026-shiny",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Shiny — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 124
  },
  {
    "path": "./writeups/boroctf-2026/whats-even-the-point/index.mdx",
    "slug": "boroctf-2026-whats-even-the-point",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "What's even the POINT? — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 169
  },
  {
    "path": "./writeups/boroctf-2026/worthful-glory/index.mdx",
    "slug": "boroctf-2026-worthful-glory",
    "ctfSlug": "boroctf-2026",
    "ctfTitle": "BoroCTF 2026",
    "writeupKind": "challenge",
    "title": "Worthful Glory — BoroCTF 2026",
    "date": "2026-06-18",
    "order": 170
  },
  {
    "path": "./writeups/byuctf-2025/index.mdx",
    "slug": "byuctf-2025",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "ctf",
    "title": "BYUCTF 2025 Writeups",
    "date": "2026-06-27",
    "order": 255
  },
  {
    "path": "./writeups/byuctf-2025/alpha/index.mdx",
    "slug": "byuctf-2025-alpha",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Alpha — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 264
  },
  {
    "path": "./writeups/byuctf-2025/anaken21sec1/index.mdx",
    "slug": "byuctf-2025-anaken21sec1",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Anaken21sec1 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 256
  },
  {
    "path": "./writeups/byuctf-2025/anaken21sec2/index.mdx",
    "slug": "byuctf-2025-anaken21sec2",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Anaken21sec2 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 257
  },
  {
    "path": "./writeups/byuctf-2025/are-you-looking-me-up/index.mdx",
    "slug": "byuctf-2025-are-you-looking-me-up",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Are You Looking Me Up? — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 287
  },
  {
    "path": "./writeups/byuctf-2025/baby-android-1/index.mdx",
    "slug": "byuctf-2025-baby-android-1",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Baby Android 1 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 272
  },
  {
    "path": "./writeups/byuctf-2025/baby-android-2/index.mdx",
    "slug": "byuctf-2025-baby-android-2",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Baby Android 2 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 273
  },
  {
    "path": "./writeups/byuctf-2025/bank-vault/index.mdx",
    "slug": "byuctf-2025-bank-vault",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Bank Vault — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 274
  },
  {
    "path": "./writeups/byuctf-2025/choose-your-rsa/index.mdx",
    "slug": "byuctf-2025-choose-your-rsa",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Choose Your RSA — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 258
  },
  {
    "path": "./writeups/byuctf-2025/cooking-flask/index.mdx",
    "slug": "byuctf-2025-cooking-flask",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Cooking Flask — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 279
  },
  {
    "path": "./writeups/byuctf-2025/cycles/index.mdx",
    "slug": "byuctf-2025-cycles",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Cycles — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 262
  },
  {
    "path": "./writeups/byuctf-2025/czech-this-out/index.mdx",
    "slug": "byuctf-2025-czech-this-out",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Czech This Out — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 290
  },
  {
    "path": "./writeups/byuctf-2025/czechxicans/index.mdx",
    "slug": "byuctf-2025-czechxicans",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Czechxicans — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 291
  },
  {
    "path": "./writeups/byuctf-2025/enabled/index.mdx",
    "slug": "byuctf-2025-enabled",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Enabled — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 265
  },
  {
    "path": "./writeups/byuctf-2025/game-of-yap/index.mdx",
    "slug": "byuctf-2025-game-of-yap",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Game of Yap — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 269
  },
  {
    "path": "./writeups/byuctf-2025/goat/index.mdx",
    "slug": "byuctf-2025-goat",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Goat — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 267
  },
  {
    "path": "./writeups/byuctf-2025/hash-based-crypto/index.mdx",
    "slug": "byuctf-2025-hash-based-crypto",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Hash Based Crypto — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 260
  },
  {
    "path": "./writeups/byuctf-2025/hash-psycho/index.mdx",
    "slug": "byuctf-2025-hash-psycho",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Hash Psycho — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 266
  },
  {
    "path": "./writeups/byuctf-2025/jwtf/index.mdx",
    "slug": "byuctf-2025-jwtf",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "JWTF — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 280
  },
  {
    "path": "./writeups/byuctf-2025/llir/index.mdx",
    "slug": "byuctf-2025-llir",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "LLIR — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 275
  },
  {
    "path": "./writeups/byuctf-2025/many-primes/index.mdx",
    "slug": "byuctf-2025-many-primes",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Many Primes — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 259
  },
  {
    "path": "./writeups/byuctf-2025/mine-over-matter/index.mdx",
    "slug": "byuctf-2025-mine-over-matter",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Mine Over Matter — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 288
  },
  {
    "path": "./writeups/byuctf-2025/minecraft-youtuber/index.mdx",
    "slug": "byuctf-2025-minecraft-youtuber",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Minecraft YouTuber — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 268
  },
  {
    "path": "./writeups/byuctf-2025/mips/index.mdx",
    "slug": "byuctf-2025-mips",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "MIPS — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 270
  },
  {
    "path": "./writeups/byuctf-2025/moooo/index.mdx",
    "slug": "byuctf-2025-moooo",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "moooo — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 276
  },
  {
    "path": "./writeups/byuctf-2025/pem/index.mdx",
    "slug": "byuctf-2025-pem",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "PEM — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 261
  },
  {
    "path": "./writeups/byuctf-2025/real-smooth/index.mdx",
    "slug": "byuctf-2025-real-smooth",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Real Smooth — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 263
  },
  {
    "path": "./writeups/byuctf-2025/red-this/index.mdx",
    "slug": "byuctf-2025-red-this",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Red This — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 282
  },
  {
    "path": "./writeups/byuctf-2025/skywim/index.mdx",
    "slug": "byuctf-2025-skywim",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Skywim — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 292
  },
  {
    "path": "./writeups/byuctf-2025/tcl/index.mdx",
    "slug": "byuctf-2025-tcl",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "TCL — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 271
  },
  {
    "path": "./writeups/byuctf-2025/u/index.mdx",
    "slug": "byuctf-2025-u",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "u — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 277
  },
  {
    "path": "./writeups/byuctf-2025/under-the-overpass/index.mdx",
    "slug": "byuctf-2025-under-the-overpass",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Under the Overpass — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 293
  },
  {
    "path": "./writeups/byuctf-2025/universal-ty/index.mdx",
    "slug": "byuctf-2025-universal-ty",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Universal-ty — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 294
  },
  {
    "path": "./writeups/byuctf-2025/wembsoncket/index.mdx",
    "slug": "byuctf-2025-wembsoncket",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wembsoncket — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 281
  },
  {
    "path": "./writeups/byuctf-2025/willy-wonka-web/index.mdx",
    "slug": "byuctf-2025-willy-wonka-web",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Willy Wonka Web — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 278
  },
  {
    "path": "./writeups/byuctf-2025/wimdows-1/index.mdx",
    "slug": "byuctf-2025-wimdows-1",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wimdows 1 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 283
  },
  {
    "path": "./writeups/byuctf-2025/wimdows-2/index.mdx",
    "slug": "byuctf-2025-wimdows-2",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wimdows 2 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 284
  },
  {
    "path": "./writeups/byuctf-2025/wimdows-3/index.mdx",
    "slug": "byuctf-2025-wimdows-3",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wimdows 3 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 285
  },
  {
    "path": "./writeups/byuctf-2025/wimdows-4/index.mdx",
    "slug": "byuctf-2025-wimdows-4",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wimdows 4 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 286
  },
  {
    "path": "./writeups/byuctf-2025/wimdows-5/index.mdx",
    "slug": "byuctf-2025-wimdows-5",
    "ctfSlug": "byuctf-2025",
    "ctfTitle": "BYUCTF 2025",
    "writeupKind": "challenge",
    "title": "Wimdows 5 — BYUCTF 2025",
    "date": "2026-06-27",
    "order": 289
  },
  {
    "path": "./writeups/byuctf-2026/index.mdx",
    "slug": "byuctf-2026",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "ctf",
    "title": "BYUCTF 2026 Writeups",
    "date": "2026-06-27",
    "order": 214
  },
  {
    "path": "./writeups/byuctf-2026/aes-scissor-co-3/index.mdx",
    "slug": "byuctf-2026-aes-scissor-co-3",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "AES Scissor Co. 3 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 231
  },
  {
    "path": "./writeups/byuctf-2026/alright-paradox-time/index.mdx",
    "slug": "byuctf-2026-alright-paradox-time",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Alright. Paradox Time — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 241
  },
  {
    "path": "./writeups/byuctf-2026/angr-management/index.mdx",
    "slug": "byuctf-2026-angr-management",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Angr Management — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 218
  },
  {
    "path": "./writeups/byuctf-2026/are-you-still-there/index.mdx",
    "slug": "byuctf-2026-are-you-still-there",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Are You Still There? — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 240
  },
  {
    "path": "./writeups/byuctf-2026/baby/index.mdx",
    "slug": "byuctf-2026-baby",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Baby — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 227
  },
  {
    "path": "./writeups/byuctf-2026/back-and-forth/index.mdx",
    "slug": "byuctf-2026-back-and-forth",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Back and Forth — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 220
  },
  {
    "path": "./writeups/byuctf-2026/bytecoin/index.mdx",
    "slug": "byuctf-2026-bytecoin",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "bytecoin — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 225
  },
  {
    "path": "./writeups/byuctf-2026/chromatic/index.mdx",
    "slug": "byuctf-2026-chromatic",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Chromatic — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 253
  },
  {
    "path": "./writeups/byuctf-2026/corrupted-cores/index.mdx",
    "slug": "byuctf-2026-corrupted-cores",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Corrupted Cores — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 242
  },
  {
    "path": "./writeups/byuctf-2026/easy/index.mdx",
    "slug": "byuctf-2026-easy",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Easy — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 251
  },
  {
    "path": "./writeups/byuctf-2026/gitastic-1/index.mdx",
    "slug": "byuctf-2026-gitastic-1",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Gitastic 1 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 234
  },
  {
    "path": "./writeups/byuctf-2026/gitastic-2/index.mdx",
    "slug": "byuctf-2026-gitastic-2",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Gitastic 2 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 235
  },
  {
    "path": "./writeups/byuctf-2026/gitastic-3/index.mdx",
    "slug": "byuctf-2026-gitastic-3",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Gitastic 3 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 236
  },
  {
    "path": "./writeups/byuctf-2026/gitastic-4/index.mdx",
    "slug": "byuctf-2026-gitastic-4",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Gitastic 4 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 237
  },
  {
    "path": "./writeups/byuctf-2026/gitastic-5/index.mdx",
    "slug": "byuctf-2026-gitastic-5",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Gitastic 5 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 238
  },
  {
    "path": "./writeups/byuctf-2026/heap2win/index.mdx",
    "slug": "byuctf-2026-heap2win",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Heap2Win — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 224
  },
  {
    "path": "./writeups/byuctf-2026/hex-to-int/index.mdx",
    "slug": "byuctf-2026-hex-to-int",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hex to Int — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 223
  },
  {
    "path": "./writeups/byuctf-2026/hometown-hero-1/index.mdx",
    "slug": "byuctf-2026-hometown-hero-1",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hometown Hero 1 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 246
  },
  {
    "path": "./writeups/byuctf-2026/hometown-hero-2/index.mdx",
    "slug": "byuctf-2026-hometown-hero-2",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hometown Hero 2 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 247
  },
  {
    "path": "./writeups/byuctf-2026/hometown-hero-3/index.mdx",
    "slug": "byuctf-2026-hometown-hero-3",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hometown Hero 3 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 248
  },
  {
    "path": "./writeups/byuctf-2026/hometown-hero-4/index.mdx",
    "slug": "byuctf-2026-hometown-hero-4",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hometown Hero 4 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 249
  },
  {
    "path": "./writeups/byuctf-2026/hometown-hero-5/index.mdx",
    "slug": "byuctf-2026-hometown-hero-5",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hometown Hero 5 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 250
  },
  {
    "path": "./writeups/byuctf-2026/hurtful/index.mdx",
    "slug": "byuctf-2026-hurtful",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Hurtful — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 232
  },
  {
    "path": "./writeups/byuctf-2026/inception/index.mdx",
    "slug": "byuctf-2026-inception",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Inception — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 254
  },
  {
    "path": "./writeups/byuctf-2026/incontinent/index.mdx",
    "slug": "byuctf-2026-incontinent",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Incontinent — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 221
  },
  {
    "path": "./writeups/byuctf-2026/intro2/index.mdx",
    "slug": "byuctf-2026-intro2",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Intro2 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 222
  },
  {
    "path": "./writeups/byuctf-2026/legoclones/index.mdx",
    "slug": "byuctf-2026-legoclones",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "LegoClones — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 243
  },
  {
    "path": "./writeups/byuctf-2026/mixed-signals/index.mdx",
    "slug": "byuctf-2026-mixed-signals",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Mixed Signals — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 219
  },
  {
    "path": "./writeups/byuctf-2026/my-cat-website/index.mdx",
    "slug": "byuctf-2026-my-cat-website",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "My Cat Website — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 226
  },
  {
    "path": "./writeups/byuctf-2026/onpoint/index.mdx",
    "slug": "byuctf-2026-onpoint",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "onpoint — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 228
  },
  {
    "path": "./writeups/byuctf-2026/pickle-rick/index.mdx",
    "slug": "byuctf-2026-pickle-rick",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Pickle Rick — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 215
  },
  {
    "path": "./writeups/byuctf-2026/power-tower/index.mdx",
    "slug": "byuctf-2026-power-tower",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Power Tower — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 230
  },
  {
    "path": "./writeups/byuctf-2026/rcaas/index.mdx",
    "slug": "byuctf-2026-rcaas",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "RCaaS — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 217
  },
  {
    "path": "./writeups/byuctf-2026/rsa-dreams/index.mdx",
    "slug": "byuctf-2026-rsa-dreams",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "RSA Dreams — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 229
  },
  {
    "path": "./writeups/byuctf-2026/scott-dourque/index.mdx",
    "slug": "byuctf-2026-scott-dourque",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Scott Dourque — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 244
  },
  {
    "path": "./writeups/byuctf-2026/scott-dourque-2/index.mdx",
    "slug": "byuctf-2026-scott-dourque-2",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Scott Dourque 2 — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 245
  },
  {
    "path": "./writeups/byuctf-2026/skull/index.mdx",
    "slug": "byuctf-2026-skull",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Skull — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 252
  },
  {
    "path": "./writeups/byuctf-2026/sus-box/index.mdx",
    "slug": "byuctf-2026-sus-box",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Sus Box — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 233
  },
  {
    "path": "./writeups/byuctf-2026/there-will-be-cake/index.mdx",
    "slug": "byuctf-2026-there-will-be-cake",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "There Will Be Cake — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 239
  },
  {
    "path": "./writeups/byuctf-2026/yet-another-recursive-algorithm/index.mdx",
    "slug": "byuctf-2026-yet-another-recursive-algorithm",
    "ctfSlug": "byuctf-2026",
    "ctfTitle": "BYUCTF 2026",
    "writeupKind": "challenge",
    "title": "Yet Another Recursive Algorithm — BYUCTF 2026",
    "date": "2026-06-27",
    "order": 216
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/index.mdx",
    "slug": "defcon-2026-qualifiers",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "ctf",
    "title": "DEF CON CTF Qualifier 2026 Writeups",
    "date": "2026-06-27",
    "order": 79
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/2bird2can/index.mdx",
    "slug": "defcon-2026-qualifiers-2bird2can",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "2bird2can — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 94
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/bird-blog/index.mdx",
    "slug": "defcon-2026-qualifiers-bird-blog",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Bird Blog — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 91
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/birdhouse/index.mdx",
    "slug": "defcon-2026-qualifiers-birdhouse",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Birdhouse — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 88
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/coalmine/index.mdx",
    "slug": "defcon-2026-qualifiers-coalmine",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "coalmine — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 82
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/coalmine-revenge/index.mdx",
    "slug": "defcon-2026-qualifiers-coalmine-revenge",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "coalmine revenge — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 86
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/gitvfs/index.mdx",
    "slug": "defcon-2026-qualifiers-gitvfs",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "gitvfs — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 83
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/gitvfs-revenge/index.mdx",
    "slug": "defcon-2026-qualifiers-gitvfs-revenge",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "gitvfs revenge — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 87
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/mapllvm/index.mdx",
    "slug": "defcon-2026-qualifiers-mapllvm",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "mapllvm — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 85
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/math-is-hard/index.mdx",
    "slug": "defcon-2026-qualifiers-math-is-hard",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Math Is Hard — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 89
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/nodefs/index.mdx",
    "slug": "defcon-2026-qualifiers-nodefs",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "nodefs — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 84
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/rfc1149a/index.mdx",
    "slug": "defcon-2026-qualifiers-rfc1149a",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "rfc1149a — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 95
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/rfc1149b/index.mdx",
    "slug": "defcon-2026-qualifiers-rfc1149b",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "rfc1149b — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 92
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/sanity-check/index.mdx",
    "slug": "defcon-2026-qualifiers-sanity-check",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Sanity Check — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 80
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/shelldiet/index.mdx",
    "slug": "defcon-2026-qualifiers-shelldiet",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "shelldiet — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 96
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/stick-drift/index.mdx",
    "slug": "defcon-2026-qualifiers-stick-drift",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Stick Drift — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 97
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/stork/index.mdx",
    "slug": "defcon-2026-qualifiers-stork",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Stork — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 81
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/the-black-talon/index.mdx",
    "slug": "defcon-2026-qualifiers-the-black-talon",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "The Black Talon — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 93
  },
  {
    "path": "./writeups/defcon-2026-qualifiers/waybird-machine/index.mdx",
    "slug": "defcon-2026-qualifiers-waybird-machine",
    "ctfSlug": "defcon-2026-qualifiers",
    "ctfTitle": "DEF CON CTF Qualifier 2026",
    "writeupKind": "challenge",
    "title": "Waybird Machine — DEF CON CTF Qualifier 2026",
    "date": "2026-06-27",
    "order": 90
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "ctf",
    "title": "NSA Codebreaker Challenge 2025-26 Writeups",
    "date": "2026-06-26",
    "order": 73
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/task1/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26-task1",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "challenge",
    "title": "Task 1: Getting Started — NSA Codebreaker Challenge 2025-26",
    "date": "2025-09-24",
    "order": 74
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/task2/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26-task2",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "challenge",
    "title": "Task 2: The Hunt Continues — NSA Codebreaker Challenge 2025-26",
    "date": "2025-09-25",
    "order": 75
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/task3/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26-task3",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "challenge",
    "title": "Task 3: Digging Deeper — NSA Codebreaker Challenge 2025-26",
    "date": "2025-09-26",
    "order": 76
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/task4/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26-task4",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "challenge",
    "title": "Task 4: Unpacking Insight — NSA Codebreaker Challenge 2025-26",
    "date": "2025-09-28",
    "order": 77
  },
  {
    "path": "./writeups/nsa-code-breaker-challenge-2025-26/task5/index.mdx",
    "slug": "nsa-code-breaker-challenge-2025-26-task5",
    "ctfSlug": "nsa-code-breaker-challenge-2025-26",
    "ctfTitle": "NSA Codebreaker Challenge 2025-26",
    "writeupKind": "challenge",
    "title": "Task 5: Going on the Offensive — NSA Codebreaker Challenge 2025-26",
    "date": "2025-09-29",
    "order": 78
  },
  {
    "path": "./writeups/picoctf-2026/index.mdx",
    "slug": "picoctf-2026",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "ctf",
    "title": "picoCTF 2026 Writeups",
    "date": "2026-06-26",
    "order": 2
  },
  {
    "path": "./writeups/picoctf-2026/absolute-nano/index.mdx",
    "slug": "picoctf-2026-absolute-nano",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "ABSOLUTE NANO — picoCTF 2026",
    "date": "2026-06-26",
    "order": 37
  },
  {
    "path": "./writeups/picoctf-2026/access-control/index.mdx",
    "slug": "picoctf-2026-access-control",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Access Control — picoCTF 2026",
    "date": "2026-06-26",
    "order": 14
  },
  {
    "path": "./writeups/picoctf-2026/autorev-1/index.mdx",
    "slug": "picoctf-2026-autorev-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Autorev 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 55
  },
  {
    "path": "./writeups/picoctf-2026/binary-digits/index.mdx",
    "slug": "picoctf-2026-binary-digits",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Binary Digits — picoCTF 2026",
    "date": "2026-06-26",
    "order": 33
  },
  {
    "path": "./writeups/picoctf-2026/binary-instrumentation-3/index.mdx",
    "slug": "picoctf-2026-binary-instrumentation-3",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Binary Instrumentation 3 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 54
  },
  {
    "path": "./writeups/picoctf-2026/binary-instrumentation-4/index.mdx",
    "slug": "picoctf-2026-binary-instrumentation-4",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Binary Instrumentation 4 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 53
  },
  {
    "path": "./writeups/picoctf-2026/black-cobra-pepper/index.mdx",
    "slug": "picoctf-2026-black-cobra-pepper",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Black Cobra Pepper — picoCTF 2026",
    "date": "2026-06-26",
    "order": 19
  },
  {
    "path": "./writeups/picoctf-2026/bypass-me/index.mdx",
    "slug": "picoctf-2026-bypass-me",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Bypass Me — picoCTF 2026",
    "date": "2026-06-26",
    "order": 59
  },
  {
    "path": "./writeups/picoctf-2026/bytemancy-0/index.mdx",
    "slug": "picoctf-2026-bytemancy-0",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "bytemancy 0 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 51
  },
  {
    "path": "./writeups/picoctf-2026/bytemancy-1/index.mdx",
    "slug": "picoctf-2026-bytemancy-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "bytemancy 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 45
  },
  {
    "path": "./writeups/picoctf-2026/bytemancy-2/index.mdx",
    "slug": "picoctf-2026-bytemancy-2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "bytemancy 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 41
  },
  {
    "path": "./writeups/picoctf-2026/bytemancy-3/index.mdx",
    "slug": "picoctf-2026-bytemancy-3",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "bytemancy 3 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 35
  },
  {
    "path": "./writeups/picoctf-2026/clusterrsa/index.mdx",
    "slug": "picoctf-2026-clusterrsa",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "ClusterRSA — picoCTF 2026",
    "date": "2026-06-26",
    "order": 15
  },
  {
    "path": "./writeups/picoctf-2026/credential-stuffing/index.mdx",
    "slug": "picoctf-2026-credential-stuffing",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Credential Stuffing — picoCTF 2026",
    "date": "2026-06-26",
    "order": 69
  },
  {
    "path": "./writeups/picoctf-2026/cryptomaze/index.mdx",
    "slug": "picoctf-2026-cryptomaze",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "cryptomaze — picoCTF 2026",
    "date": "2026-06-26",
    "order": 26
  },
  {
    "path": "./writeups/picoctf-2026/disko-4/index.mdx",
    "slug": "picoctf-2026-disko-4",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "DISKO 4 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 31
  },
  {
    "path": "./writeups/picoctf-2026/echo-escape-1/index.mdx",
    "slug": "picoctf-2026-echo-escape-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Echo Escape 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 7
  },
  {
    "path": "./writeups/picoctf-2026/echo-escape-2/index.mdx",
    "slug": "picoctf-2026-echo-escape-2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Echo Escape 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 8
  },
  {
    "path": "./writeups/picoctf-2026/failure-failure/index.mdx",
    "slug": "picoctf-2026-failure-failure",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Failure Failure — picoCTF 2026",
    "date": "2026-06-26",
    "order": 38
  },
  {
    "path": "./writeups/picoctf-2026/fool-the-lockout/index.mdx",
    "slug": "picoctf-2026-fool-the-lockout",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Fool the Lockout — picoCTF 2026",
    "date": "2026-06-26",
    "order": 66
  },
  {
    "path": "./writeups/picoctf-2026/forensics-git-0/index.mdx",
    "slug": "picoctf-2026-forensics-git-0",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Forensics Git 0 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 32
  },
  {
    "path": "./writeups/picoctf-2026/forensics-git-1/index.mdx",
    "slug": "picoctf-2026-forensics-git-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Forensics Git 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 28
  },
  {
    "path": "./writeups/picoctf-2026/forensics-git-2/index.mdx",
    "slug": "picoctf-2026-forensics-git-2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Forensics Git 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 27
  },
  {
    "path": "./writeups/picoctf-2026/front-running/index.mdx",
    "slug": "picoctf-2026-front-running",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Front Running — picoCTF 2026",
    "date": "2026-06-26",
    "order": 12
  },
  {
    "path": "./writeups/picoctf-2026/gatekeeper/index.mdx",
    "slug": "picoctf-2026-gatekeeper",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Gatekeeper — picoCTF 2026",
    "date": "2026-06-26",
    "order": 60
  },
  {
    "path": "./writeups/picoctf-2026/hashgate/index.mdx",
    "slug": "picoctf-2026-hashgate",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Hashgate — picoCTF 2026",
    "date": "2026-06-26",
    "order": 70
  },
  {
    "path": "./writeups/picoctf-2026/heap-havoc/index.mdx",
    "slug": "picoctf-2026-heap-havoc",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Heap Havoc — picoCTF 2026",
    "date": "2026-06-26",
    "order": 6
  },
  {
    "path": "./writeups/picoctf-2026/hidden-cipher-1/index.mdx",
    "slug": "picoctf-2026-hidden-cipher-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Hidden Cipher 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 61
  },
  {
    "path": "./writeups/picoctf-2026/hidden-cipher-2/index.mdx",
    "slug": "picoctf-2026-hidden-cipher-2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Hidden Cipher 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 62
  },
  {
    "path": "./writeups/picoctf-2026/jitfp/index.mdx",
    "slug": "picoctf-2026-jitfp",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "JITFP — picoCTF 2026",
    "date": "2026-06-26",
    "order": 52
  },
  {
    "path": "./writeups/picoctf-2026/ksecrets/index.mdx",
    "slug": "picoctf-2026-ksecrets",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "KSECRETS — picoCTF 2026",
    "date": "2026-06-26",
    "order": 42
  },
  {
    "path": "./writeups/picoctf-2026/mss-advance-revenge/index.mdx",
    "slug": "picoctf-2026-mss-advance-revenge",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "MSS ADVANCE Revenge — picoCTF 2026",
    "date": "2026-06-26",
    "order": 16
  },
  {
    "path": "./writeups/picoctf-2026/multicode/index.mdx",
    "slug": "picoctf-2026-multicode",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "MultiCode — picoCTF 2026",
    "date": "2026-06-26",
    "order": 39
  },
  {
    "path": "./writeups/picoctf-2026/my-git/index.mdx",
    "slug": "picoctf-2026-my-git",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "MY GIT — picoCTF 2026",
    "date": "2026-06-26",
    "order": 47
  },
  {
    "path": "./writeups/picoctf-2026/no-fa/index.mdx",
    "slug": "picoctf-2026-no-fa",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "No FA — picoCTF 2026",
    "date": "2026-06-26",
    "order": 67
  },
  {
    "path": "./writeups/picoctf-2026/north-south/index.mdx",
    "slug": "picoctf-2026-north-south",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "North-South — picoCTF 2026",
    "date": "2026-06-26",
    "order": 71
  },
  {
    "path": "./writeups/picoctf-2026/not-true/index.mdx",
    "slug": "picoctf-2026-not-true",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Not TRUe — picoCTF 2026",
    "date": "2026-06-26",
    "order": 17
  },
  {
    "path": "./writeups/picoctf-2026/offset-cycle/index.mdx",
    "slug": "picoctf-2026-offset-cycle",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "offset-cycle — picoCTF 2026",
    "date": "2026-06-26",
    "order": 5
  },
  {
    "path": "./writeups/picoctf-2026/offset-cyclev2/index.mdx",
    "slug": "picoctf-2026-offset-cyclev2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "offset-cycle V2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 4
  },
  {
    "path": "./writeups/picoctf-2026/old-sessions/index.mdx",
    "slug": "picoctf-2026-old-sessions",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Old Sessions — picoCTF 2026",
    "date": "2026-06-26",
    "order": 72
  },
  {
    "path": "./writeups/picoctf-2026/order-order/index.mdx",
    "slug": "picoctf-2026-order-order",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "ORDER ORDER — picoCTF 2026",
    "date": "2026-06-26",
    "order": 64
  },
  {
    "path": "./writeups/picoctf-2026/paper2/index.mdx",
    "slug": "picoctf-2026-paper2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Paper 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 63
  },
  {
    "path": "./writeups/picoctf-2026/password-profiler/index.mdx",
    "slug": "picoctf-2026-password-profiler",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Password Profiler — picoCTF 2026",
    "date": "2026-06-26",
    "order": 43
  },
  {
    "path": "./writeups/picoctf-2026/piece-by-piece/index.mdx",
    "slug": "picoctf-2026-piece-by-piece",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Piece by Piece — picoCTF 2026",
    "date": "2026-06-26",
    "order": 48
  },
  {
    "path": "./writeups/picoctf-2026/ping-cmd/index.mdx",
    "slug": "picoctf-2026-ping-cmd",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "ping-cmd — picoCTF 2026",
    "date": "2026-06-26",
    "order": 46
  },
  {
    "path": "./writeups/picoctf-2026/pizza-router/index.mdx",
    "slug": "picoctf-2026-pizza-router",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Pizza Router — picoCTF 2026",
    "date": "2026-06-26",
    "order": 3
  },
  {
    "path": "./writeups/picoctf-2026/printer-shares/index.mdx",
    "slug": "picoctf-2026-printer-shares",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Printer Shares — picoCTF 2026",
    "date": "2026-06-26",
    "order": 49
  },
  {
    "path": "./writeups/picoctf-2026/printer-shares-2/index.mdx",
    "slug": "picoctf-2026-printer-shares-2",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Printer Shares 2 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 40
  },
  {
    "path": "./writeups/picoctf-2026/printer-shares-3/index.mdx",
    "slug": "picoctf-2026-printer-shares-3",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Printer Shares 3 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 36
  },
  {
    "path": "./writeups/picoctf-2026/quizploit/index.mdx",
    "slug": "picoctf-2026-quizploit",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Quizploit — picoCTF 2026",
    "date": "2026-06-26",
    "order": 10
  },
  {
    "path": "./writeups/picoctf-2026/reentrance/index.mdx",
    "slug": "picoctf-2026-reentrance",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Reentrance — picoCTF 2026",
    "date": "2026-06-26",
    "order": 11
  },
  {
    "path": "./writeups/picoctf-2026/related-messages/index.mdx",
    "slug": "picoctf-2026-related-messages",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Related Messages — picoCTF 2026",
    "date": "2026-06-26",
    "order": 20
  },
  {
    "path": "./writeups/picoctf-2026/rogue-tower/index.mdx",
    "slug": "picoctf-2026-rogue-tower",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Rogue Tower — picoCTF 2026",
    "date": "2026-06-26",
    "order": 29
  },
  {
    "path": "./writeups/picoctf-2026/secret-box/index.mdx",
    "slug": "picoctf-2026-secret-box",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Secret Box — picoCTF 2026",
    "date": "2026-06-26",
    "order": 68
  },
  {
    "path": "./writeups/picoctf-2026/secure-dot-product/index.mdx",
    "slug": "picoctf-2026-secure-dot-product",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Secure Dot Product — picoCTF 2026",
    "date": "2026-06-26",
    "order": 18
  },
  {
    "path": "./writeups/picoctf-2026/secure-password-database/index.mdx",
    "slug": "picoctf-2026-secure-password-database",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Secure Password Database — picoCTF 2026",
    "date": "2026-06-26",
    "order": 56
  },
  {
    "path": "./writeups/picoctf-2026/shared-secrets/index.mdx",
    "slug": "picoctf-2026-shared-secrets",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Shared Secrets — picoCTF 2026",
    "date": "2026-06-26",
    "order": 24
  },
  {
    "path": "./writeups/picoctf-2026/shift-registers/index.mdx",
    "slug": "picoctf-2026-shift-registers",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "shift registers — picoCTF 2026",
    "date": "2026-06-26",
    "order": 23
  },
  {
    "path": "./writeups/picoctf-2026/silent-stream/index.mdx",
    "slug": "picoctf-2026-silent-stream",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Silent Stream — picoCTF 2026",
    "date": "2026-06-26",
    "order": 57
  },
  {
    "path": "./writeups/picoctf-2026/small-trouble/index.mdx",
    "slug": "picoctf-2026-small-trouble",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Small Trouble — picoCTF 2026",
    "date": "2026-06-26",
    "order": 21
  },
  {
    "path": "./writeups/picoctf-2026/smart-overflow/index.mdx",
    "slug": "picoctf-2026-smart-overflow",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Smart Overflow — picoCTF 2026",
    "date": "2026-06-26",
    "order": 13
  },
  {
    "path": "./writeups/picoctf-2026/sql-map1/index.mdx",
    "slug": "picoctf-2026-sql-map1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Sql Map1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 65
  },
  {
    "path": "./writeups/picoctf-2026/stegorsa/index.mdx",
    "slug": "picoctf-2026-stegorsa",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "StegoRSA — picoCTF 2026",
    "date": "2026-06-26",
    "order": 25
  },
  {
    "path": "./writeups/picoctf-2026/sudo-make-me-a-sandwich/index.mdx",
    "slug": "picoctf-2026-sudo-make-me-a-sandwich",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "SUDO MAKE ME A SANDWICH — picoCTF 2026",
    "date": "2026-06-26",
    "order": 50
  },
  {
    "path": "./writeups/picoctf-2026/tea-cash/index.mdx",
    "slug": "picoctf-2026-tea-cash",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "tea-cash — picoCTF 2026",
    "date": "2026-06-26",
    "order": 9
  },
  {
    "path": "./writeups/picoctf-2026/the-add-on-trap/index.mdx",
    "slug": "picoctf-2026-the-add-on-trap",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "The Add-On Trap — picoCTF 2026",
    "date": "2026-06-26",
    "order": 58
  },
  {
    "path": "./writeups/picoctf-2026/timeline-0/index.mdx",
    "slug": "picoctf-2026-timeline-0",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Timeline 0 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 34
  },
  {
    "path": "./writeups/picoctf-2026/timeline-1/index.mdx",
    "slug": "picoctf-2026-timeline-1",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Timeline 1 — picoCTF 2026",
    "date": "2026-06-26",
    "order": 30
  },
  {
    "path": "./writeups/picoctf-2026/timestamped-secrets/index.mdx",
    "slug": "picoctf-2026-timestamped-secrets",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Timestamped Secrets — picoCTF 2026",
    "date": "2026-06-26",
    "order": 22
  },
  {
    "path": "./writeups/picoctf-2026/undo/index.mdx",
    "slug": "picoctf-2026-undo",
    "ctfSlug": "picoctf-2026",
    "ctfTitle": "picoCTF 2026",
    "writeupKind": "challenge",
    "title": "Undo — picoCTF 2026",
    "date": "2026-06-26",
    "order": 44
  }
] as const;
